# Generated by Django 5.2.17 on 2026-09-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('medicine', models.CharField(blank=True, max_length=160)),
                ('strength', models.CharField(blank=True, max_length=80)),
                ('quantity', models.CharField(blank=True, max_length=80)),
                ('dosage', models.CharField(blank=True, max_length=240)),
                ('duration', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
