# Generated by Django 5.2.17 on 2026-09-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='prescription',
            name='source_type',
            field=models.CharField(default='text', max_length=20),
        ),
    ]
